/*
Copyright AppsCode Inc. and Contributors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
	v1alpha1 "kubeops.dev/sidekick/apis/apps/v1alpha1"
	scheme "kubeops.dev/sidekick/client/clientset/versioned/scheme"
)

// SidekicksGetter has a method to return a SidekickInterface.
// A group's client should implement this interface.
type SidekicksGetter interface {
	Sidekicks(namespace string) SidekickInterface
}

// SidekickInterface has methods to work with Sidekick resources.
type SidekickInterface interface {
	Create(ctx context.Context, sidekick *v1alpha1.Sidekick, opts v1.CreateOptions) (*v1alpha1.Sidekick, error)
	Update(ctx context.Context, sidekick *v1alpha1.Sidekick, opts v1.UpdateOptions) (*v1alpha1.Sidekick, error)
	UpdateStatus(ctx context.Context, sidekick *v1alpha1.Sidekick, opts v1.UpdateOptions) (*v1alpha1.Sidekick, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.Sidekick, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.SidekickList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Sidekick, err error)
	SidekickExpansion
}

// sidekicks implements SidekickInterface
type sidekicks struct {
	client rest.Interface
	ns     string
}

// newSidekicks returns a Sidekicks
func newSidekicks(c *AppsV1alpha1Client, namespace string) *sidekicks {
	return &sidekicks{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the sidekick, and returns the corresponding sidekick object, and an error if there is any.
func (c *sidekicks) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.Sidekick, err error) {
	result = &v1alpha1.Sidekick{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("sidekicks").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Sidekicks that match those selectors.
func (c *sidekicks) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.SidekickList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.SidekickList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("sidekicks").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested sidekicks.
func (c *sidekicks) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("sidekicks").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a sidekick and creates it.  Returns the server's representation of the sidekick, and an error, if there is any.
func (c *sidekicks) Create(ctx context.Context, sidekick *v1alpha1.Sidekick, opts v1.CreateOptions) (result *v1alpha1.Sidekick, err error) {
	result = &v1alpha1.Sidekick{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("sidekicks").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(sidekick).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a sidekick and updates it. Returns the server's representation of the sidekick, and an error, if there is any.
func (c *sidekicks) Update(ctx context.Context, sidekick *v1alpha1.Sidekick, opts v1.UpdateOptions) (result *v1alpha1.Sidekick, err error) {
	result = &v1alpha1.Sidekick{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("sidekicks").
		Name(sidekick.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(sidekick).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *sidekicks) UpdateStatus(ctx context.Context, sidekick *v1alpha1.Sidekick, opts v1.UpdateOptions) (result *v1alpha1.Sidekick, err error) {
	result = &v1alpha1.Sidekick{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("sidekicks").
		Name(sidekick.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(sidekick).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the sidekick and deletes it. Returns an error if one occurs.
func (c *sidekicks) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("sidekicks").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *sidekicks) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("sidekicks").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched sidekick.
func (c *sidekicks) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Sidekick, err error) {
	result = &v1alpha1.Sidekick{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("sidekicks").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
