apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: busy-dep
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: linode-block-storage-retain
  volumeMode: Filesystem
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: busy-dep
  labels:
    app: busy-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: busy-dep
  template:
    metadata:
      labels:
        app: busy-dep
    spec:
      containers:
      - image: busybox
        command:
          - sleep
          - "3600"
        imagePullPolicy: IfNotPresent
        name: busybox
        volumeMounts:
        - mountPath: /cache
          name: cache-volume
      - image: ubuntu:18.04
        command:
          - sleep
          - "3600"
        imagePullPolicy: IfNotPresent
        name: ubuntu
      restartPolicy: Always
      volumes:
      - name: cache-volume
        persistentVolumeClaim:
          claimName: busy-dep
