# permissions for end users to edit sidekicks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: sidekick-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: sidekick
    app.kubernetes.io/part-of: sidekick
    app.kubernetes.io/managed-by: kustomize
  name: sidekick-editor-role
rules:
- apiGroups:
  - apps.k8s.appscode.com
  resources:
  - sidekicks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.k8s.appscode.com
  resources:
  - sidekicks/status
  verbs:
  - get
