---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - apps.k8s.appscode.com
  resources:
  - sidekicks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.k8s.appscode.com
  resources:
  - sidekicks/finalizers
  verbs:
  - update
- apiGroups:
  - apps.k8s.appscode.com
  resources:
  - sidekicks/status
  verbs:
  - get
  - patch
  - update
